name: Update Monaco-editor
on:
  workflow_dispatch:
  push:
    branches:
      - 'dependabot/npm_and_yarn/develop/monaco-editor-**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Update monaco version
        run: |
          yarn install
          node ./bin/update-monaco.js
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: 'Update Monaco-editor'
